[package]
name = "buzzerapp"
version = "0.1.0"
authors = ["Alexandros Katechis <akatechis@gmail.com>"]

[dependencies]
ws = "0.7"
log = "0.4"
env_logger = "0.5"
md5 = "0.3"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
rusqlite = { version = "0.13", features = ["bundled"]}
